### ISSUE TITLE
Forecast Module: Spaces in city name

### ISSUE THREAD

**Issue by rbtylee** [JeffHoogland/moksha-modules-extra#19]
A commit by thewaiter,[ 47d2886](https://github.com/thewaiter/moksha-modules-extra/commit/47d28869e037faf4d90a7ad1f7e25018c5b6867b) introduces a bug when selecting location by city name. City names that contain spaces result in a malformed yahoo weather api query url. Hence the returned xml file is either incorrect or not found. Test case is 'San Francisco'. Location is not found. But 'San%20Francisco' is found.

**Comment by rbtylee** [comment]
I don't have access here but I do on thewaiters fork, but will commit a fix there, ASAP.

**Comment by thewaiter** [comment]
If I am right we could close this issue as it was fixed on commit
https://github.com/JeffHoogland/moksha-modules-extra/commit/bcb5ea05ae1f130fc874cbc1cf52d8569428cb44
