### ISSUE TITLE
diskio: e_mod_main.c:426:4: error: format not a string literal and no format arguments

### ISSUE THREAD

**Issue by srakitnican** [JeffHoogland/moksha-modules-extra#24]
```
e_mod_main.c: In function '_diskio_set':
e_mod_main.c:249:9: warning: unused variable 'dummy' [-Wunused-variable]
    char dummy[16];
         ^~~~~
e_mod_main.c: In function '_diskio_conf_new':
e_mod_main.c:379:9: warning: unused variable 'buf' [-Wunused-variable]
    char buf[128];
         ^~~
e_mod_main.c:378:17: warning: unused variable 'ci' [-Wunused-variable]
    Config_Item *ci = NULL;
                 ^~
e_mod_main.c: In function '_diskio_conf_timer':
e_mod_main.c:426:4: error: format not a string literal and no format arguments [-Werror=format-security]
    e_util_dialog_show( D_("DiskIO Configuration Updated"), data);
    ^~~~~~~~~~~~~~~~~~
e_mod_main.c: In function '_diskio_set':
e_mod_main.c:270:4: warning: ignoring return value of 'fgets', declared with attribute warn_unused_result [-Wunused-result]
    fgets(buffer, sizeof(buffer), statfile);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by thewaiter** [comment]
Hello, tell me the EFL and E version you have compiled the module please.

**Comment by srakitnican** [comment]
Hi, E stands for enlightenment I presume, I am using moksha instead. I am trying to package it for Fedora.
```
efl-1.19.0
moksha-desktop-0.2.1
```
So the issue is that Fedora default compiler flags adds hardening flags like -Werror=format-security, which gives this error I presume. Other thing that may affect it is gcc I think, Fedora 25 comes with `gcc-6.4.1`.

**Comment by thewaiter** [comment]
Hello, check the last commit please...

**Comment by srakitnican** [comment]
Code compiles now. Thanks.

I've noticed there are also a bunch of `-Wmisleading-indentation` warnings, but I am not able to tell if it is a problem or not. Should I open a separate issue for that?

https://copr-be.cloud.fedoraproject.org/results/srakitnican/moksha-desktop/fedora-26-x86_64/00610434-moksha-modules-extra/build.log.gz

**Comment by thewaiter** [comment]
I think there is a mistake, it should be:
if (!ev->new)
     return EINA_FALSE; 
else
     return EINA_TRUE;

**Comment by srakitnican** [comment]
Sorry for not replying earlier, kind of forgot. Yes, this makes the warning go away.
```c
   if (!ev->new)
     return EINA_FALSE;
   else
     return EINA_TRUE;
```
