### ISSUE TITLE
Hardcoded `/usr/local/share/`

### ISSUE THREAD

**Issue by srakitnican** [JeffHoogland/moksha-modules-extra#25]
There is a hardcoded `/usr/local/share/` in couple of places, ideally build system should respect options and modify files accordingly such as `--datadir=/usr/share`.

https://github.com/JeffHoogland/moksha-modules-extra/search?utf8=✓&q="%2Fusr%2Flocal%2Fshare%2F"&type=

In the case of `emprint/images/Camera.wav` build system respects command line flag, but with binary having a hardcoded path, it will always look for the file in `/usr/local/share/` location.

**Comment by JeffHoogland** [comment]
Feel free to submit a patch.

**Comment by thewaiter** [comment]
Yes, it was my work. Lack of autotools skills did not allow me do that properly. As Jeff pointed, feel free to make a patch...

**Comment by srakitnican** [comment]
Hi, I think is very simple, I've spend some time and researched how could it be done, unfortunately I lack C skills to implement it, but I can give a patch for autotools if it helps.

For the `mail` module it seems like original script missuses `datadir` variable and makes it into a module path. Since it is implemented in basically all modules as seems, I didn't try to fix that, but instead just made use of it for data files as well. With following patch there is `PACKAGE_MOD_DIR` variable available through a header file `config.h` which is included at build time. For the `emprint` module there is a slightly different variable `PACKAGE_DATA_DIR` already available which can be used for this purpose.

[0001-mail-Fix-build-system-to-be-flexible-on-location-of-.patch.txt](https://github.com/JeffHoogland/moksha-modules-extra/files/1322255/0001-mail-Fix-build-system-to-be-flexible-on-location-of-.patch.txt)

**Comment by thewaiter** [comment]
Patch applied and I also made changes in code (thx okra). Check the commits and close the issue if OK...

**Comment by srakitnican** [comment]
Seems to work fine, thank you.

**Comment by JeffHoogland** [comment]
Resolved via https://github.com/JeffHoogland/moksha-modules-extra/commit/800f90daf66e6055d4b7d785927c7ce184ff9202
