### ISSUE TITLE
screenshot: Not a build dependency: emprint

### ISSUE THREAD

**Issue by srakitnican** [JeffHoogland/moksha-modules-extra#26]
`screenshot` build system is looking for `emprint` dependency, but I believe it is a runtime dependency, not necessary in build time. Since I am building the sources for modules all at once, this is a problem since nothing yet provides `emprint`.

Solution: If `emprint` is indeed unneeded at build time for `screenshot`, remove the dependency from build system.

**Comment by JeffHoogland** [comment]
Fairly certain that you are correct that this is a run time dependency only. Feel free to make a pull request correcting this.

**Comment by JeffHoogland** [comment]
Resolved via https://github.com/JeffHoogland/moksha-modules-extra/commit/86e12bd42f23fca862a39569f0ba00c416b41cb1
