### ISSUE TITLE
Loaded modules doesn't appear in taskbar

### ISSUE THREAD

**Issue by srakitnican** [JeffHoogland/moksha-modules-extra#27]
While trying to load modules, while it seems module loaded successfully, nothing appears in the taskbar for modules with an icon. I believe few modules work correctly that doesn't need icon in taskbar such as: flames, penguins, rain, snow... By looking at system log, nothing obvious appears except messages flood that happens regardless of modules state. https://github.com/JeffHoogland/moksha/issues/53 . Sometimes desktop seems to restart itself while configuring.

Anyone have an idea how to debug this, since these modules appears to work for anyone else it must be something specific to my environment, right?

I've also tried to build using supplied script `autogen.sh`, got the same results.

* EFL 1.19.0
* Moksha 0.2.1

**Comment by thewaiter** [comment]
Hmm, do you have the same prefix path set in case of moksha and modules? I can remember, once I set the Moksha prefix to /usr/share/local and modules loaded, but they stayed unvisible.
Anyway, try to follow this link for more info about Moksha under Fedora
http://forums.bodhilinux.com/index.php?/topic/12829-building-moksha-under-fedora-23-eina-library-not-found/

**Comment by JeffHoogland** [comment]
Which modules are you loading that aren't working specifically?

**Comment by thewaiter** [comment]
Moment, I think this is a misunderstanding. Loading modules is one thing and showing the second one. Almost no extra module is gonna show its gadget on the shelf or desktop. You have to place its gadget manually. 
If you want to place gadget to the shelf, right click on the free part of the shelf, contents and choose the gadget you wanna add...
If you want to place gadget on the desktop, main menu-settings-gadget-background and select the gadget.

**Comment by srakitnican** [comment]
Right, sorry I am E newbie :D

**Comment by thewaiter** [comment]
np. Maybe a better way is login to Bodhi Linux forum, for perhaps better feedback.
