### ISSUE TITLE
Icon CPU module

### ISSUE THREAD

**Issue by jh1234567890** [JeffHoogland/moksha-modules-extra#34]
I like to modify the icon in the tray because it to confuse the background image with processor percent use. 

It's possible ?

Thanks

**Comment by thewaiter** [comment]
Hello there
Yes, it is possible, but you need to decode edj file, change the icon picture (or text color) and code back. I will post the method when I get home and have some time.

Stefan

**Comment by jh1234567890** [comment]
Hello

It's here ?

/media/sda3/usr/lib/x86_64-linux-gnu/enlightenment/modules/cpu/e-module-cpu.edj

/media/sda3/usr/lib/x86_64-linux-gnu/enlightenment/modules/cpu/cpu.edj

I don't edit it with anny programm ( Gimp, ed )

Sorry my bad english, I brazilian ... :-)

**Comment by thewaiter** [comment]
Hello there
Yes, you have found it. Now the method:
1. copy /media/sda3/usr/lib/x86_64-linux-gnu/enlightenment/modules/cpu/cpu.edj to some tmp folder
2. cd to tmp and use this command to depack edj container: edje_decc cpu.edj
3. cpu folder will be created
4. cd to cpu and you can see image, edc file and build script
5. change the image to your own
6. pack edj back running ./build.sh script 
7. sudo copy edj file back to module folder /usr/lib/x86...

Enjoy :)

Stefan
BTW feel free to ask any question on https://www.linuxquestions.org/questions/bodhi-92/

**Comment by jh1234567890** [comment]
I

Sorry, not work  ...

I editing it and put it in the folder and the icon hidden in the ibar

**Comment by thewaiter** [comment]
Hmm, not sure which step is problematic so one again

1. create tmp dir in your home dir: mkdir tmp  
2. cp /media/sda3/usr/lib/x86_64-linux-gnu/enlightenment/modules/cpu/cpu.edj ~/tmp 
3. cd tmp 
4. edje_decc cpu.edj
5. cd cpu 
6. change the image to your own
7 ./build.sh script
8. sudo cp cpu.edj /media/sda3/usr/lib/x86_64-linux-gnu/enlightenment/modules/cpu

Good luck
Stefan

**Comment by jh1234567890** [comment]
[Icons.zip](https://github.com/JeffHoogland/moksha-modules-extra/files/4027366/Icons.zip)

The icons are atached ( the original and edited ), please verify for me it correct 

Thanks

**Comment by thewaiter** [comment]
OK, you did everything right. Just you need to rename cpu-edit.edj to cpu.edj and then copy to module destination. I tried your edj on my Bodhi with this result:
https://i.imgur.com/rLFENrb.jpg

**Comment by thewaiter** [comment]
Oh, I know what I forgot to tell you (probably as a developer I did this thousands times and it is too common for me). After the method you need to restart moksha desktop from menu or simply ctrl alt end combination to reload the module. I hope this should help

Stefan

**Comment by jh1234567890** [comment]
Hello

I tried it too but no work ...

See

https://postimg.cc/ZvBstZJF

**Comment by thewaiter** [comment]
hmm, hard to understand why does not work. Best way is a remote screen via team viewer and try it by myself if you really need to solve it. Contact me on thewaiter@centrum.sk

**Comment by thewaiter** [comment]
Too private request. Not reproducible. I am closing the issue
