### ISSUE TITLE
Error loading module Engage

### ISSUE THREAD

**Issue by AdriandMartin** [JeffHoogland/moksha-modules-extra#36]
I got an error when Moksha desktop (version 0.3.2) started and Engage failed to load. I updated Moksha two days ago and Engage worked fine before that. The problems came when I restarted the computer and Engage had to be loaded again. Attached a screenshot of the failure
![engage-dock_issue](https://user-images.githubusercontent.com/22200464/103143769-558f2400-471d-11eb-8a1d-ec062c5f60b2.png)

**Comment by thewaiter** [comment]
Hello Adriand
There was a bug in Engage code. New gcc version identified it. I had to made some changes to moksha code. The only problem was, the moksha package was done sooner than the engage one :)
Now, th solution is very easy. Update repo and upgrade system or just moksha-module-engage. It should be OK 

Stefan

PS: Let me know the feedbackj after upgrade

**Comment by AdriandMartin** [comment]
I just updated the Engage module, I loaded it through the configuration and everything works perfectly. Thank you very much for the quick answer :)
