### ISSUE TITLE
Slideshow Module Has resolution problems

### ISSUE THREAD

**Issue by MaxineJamestone** [JeffHoogland/moksha-modules-extra#41]
![image](https://user-images.githubusercontent.com/98226999/151235593-0b15af4a-ce3d-45ec-9663-396d35f97533.png)
All images seem extremely low res. That includes 4k ones

**Comment by rbtylee** [comment]
Interesting. We will look into this as time permits.

**Comment by thewaiter** [comment]
Solved in https://github.com/JeffHoogland/moksha/commit/2043261afde837915d6ffe59d4b607b1f26862d5
