### ISSUE TITLE
Screenshot module: Unable to press Esc to quit region select 

### ISSUE THREAD

**Issue by dinesh-58** [JeffHoogland/moksha-modules-extra#44]
This happens when delay time is set to 0 seconds. Setting to 1 or more allows for quitting using Esc. Also, turning off the beep while taking screenshot doesn't work. This is on Bodhi Linux.

**Comment by thewaiter** [comment]
OK, thx for feedbak. We will check the settings and fix if possible...
Stefan

**Comment by thewaiter** [comment]
Sound on/off fixed
https://github.com/JeffHoogland/moksha-modules-extra/commit/ac9a0f5b095bd5f2d087635fb99b2a3e46436e14

**Comment by thewaiter** [comment]
Not sure about ESC region. I set delay to 0 and I can exit the capture mode... May I see the screencast pls?

**Comment by dinesh-58** [comment]
https://user-images.githubusercontent.com/86787475/190640571-7c4c319a-c380-4e8e-853d-403966d75d13.mp4

The mouse pointer only changes to normal after I press it & take a screenshot.

**Comment by thewaiter** [comment]
Interesting. Once I press Esc, the cross switches to normal mouse cursor here. You need to press ESC multiple times?

**Comment by dinesh-58** [comment]
Not really. It doesn't switch to normal even after multiple Esc presses. It only switches because I pressed left mouse and it took a screenshot.

**Comment by thewaiter** [comment]
Hmm, I really do not know what should I think about it. I tried multiple times the region capture mode with 0 delay and ESC works absolutely correctly here. Sorry, there is nothing to fix here...

**Comment by hippytaffer** [comment]
Can't reproduce the issue here either. Works as expected with the same settings.
![shot-2022-09-17_23-22-21](https://user-images.githubusercontent.com/59973741/190878235-a9808afa-3fb8-4839-9ebe-66704ed4be4d.jpg)

**Comment by dinesh-58** [comment]
Might be a problem with my installation. I'll try reinstalling later.

**Comment by dinesh-58** [comment]
Still doesn't work for some reason. I'm okay with 1 second delay for the screenshot.

**Comment by thewaiter** [comment]
I am able to reproduce the issue. You activate the feature via key bindings while I activated by mouse click on the gadget. The glitch was identified and fixed. 
https://github.com/JeffHoogland/moksha-modules-extra/commit/f7e5c27fa3715af8691005aedf74864b28893571
THX :)
